### ISSUE TITLE
Windows Usage

### ISSUE THREAD

**Issue by chjones45** [s3tester/s3tester#17]
There is an executable for Windows, however how do we specify the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as they do not seem to be parameters we can pass in the cli and "export" does not work in Windows.

**Comment by vmore** [comment]
Look at the -profile option. It will let you use a credentials file https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
